### ISSUE TITLE
Problems trying to use MongloDB

### ISSUE THREAD

**Issue by john-dalsgaard** [Monglo/MongloDB#3]
Hi

I know this may be a bad timing since it says "Refactoring in progress...". But I really think MongloDb would be most interesting for the Appcelerator Titanium development I do right now. So either I am trying to install it incorrectly, or it is due to the process of being refactored.

So far, I have created a "Monglo" directory under my "lib" folder in Titanium (I am using Alloy), and added all the files from the lib folder here into that folder. I am using that folder as a result of following the Appcelerator Titanium Business Application Development Cookbook that seems to expect the files to be in this folder.

I have also tried to use the code in the readme on Monglodb.com to initialize and use the database (preferably with a datastore). But so far, I have had no success. Right now I get "Script Error Couldn't find module: emitter".

Is this due to the refactoring? Or is it just because I don't know how to copy the files correctly into my project and use them in my app.?

Thanks in advance for any help you can provide ;-)

/John

**Comment by ccalvarez** [comment]
Hi, 
Did you find a solution for this issue? I'm facing the same inconvenient.
Thanks.

**Comment by john-dalsgaard** [comment]
Hi,
No, as you can see I never got a response. So I ended up using SculeJS instead. It seems more "ready".
/John

**Comment by euforic** [comment]
@john-dalsgaard @ccalvarez sorry for the lack of response I was no longer getting email updates from the repo. I have updated the project fixing the build. you should just be able to clone now `cd` into the project folder run `npm install && make` and it should generate a usable build
