### ISSUE TITLE
Somebody working on this?

### ISSUE THREAD

**Issue by tiptronic** [Monglo/MongloDB#4]

**Comment by neptuwunium** [comment]
Doesn't seem like it

**Comment by euforic** [comment]
@tiptronic sorry the project has been partially abandoned, but I we are open to adding contributors with push access.

**Comment by ccalvarez** [comment]
@euforic hi, but is this library working at least?  I am trying to run it, I've "run npm install" but it didn't downloaded the file emitter.js, so I don't know if I have to do something with Makefile.

Could you help me to get this library running?
Thanks.

**Comment by euforic** [comment]
@tiptronic @yukimono @ccalvarez I have updated the project to fix the build issues and also included a precompiled version in the dist folder. I have also updated the titanium store fixing the build issues.
