### ISSUE TITLE
Is this version stable?

### ISSUE THREAD

**Issue by ccalvarez** [Monglo/MongloDB#5]
@euforic hi, is this library working? I am trying to use it, I've "run npm install" but it didn't downloaded the file emitter.js, so I don't know if I have to do something with Makefile.

Could you help me to get this library running?
Thanks.

**Comment by john-dalsgaard** [comment]
Hi, I tried to get this working a while back - but gave up for some of the same reasons as you experience. I ended up using "Scule.js" instead (http://sculejs.org/) which so far seems to be working fine ;-)

/John

**Comment by ccalvarez** [comment]
Thank you John.
Do you know if a Scule.js store can be stored in an external media device like a USB flash drive?  I know it is a little bit contradictory with the normal use for a web browser but I need to meet this user requirement.
Thanks for your help.

**Comment by john-dalsgaard** [comment]
No, I am afraid I don't. I use it from Titanium on mobile devices ;-)

**Comment by euforic** [comment]
updated readme and fixed builder see #3
